### ISSUE TITLE
Delta V Text Overlap in Mk1 (and maybe others)

### ISSUE THREAD

**Issue by Marco-Zechner** [JonnyOThan/DE_IVAExtension#3]
![image](https://github.com/user-attachments/assets/936ec02f-414d-4b2d-bc2c-811c8ecb0f01)

Also "DROPMASS" that is behind has possibly no value.

**Comment by JonnyOThan** [comment]
This is a problem for ASET props: https://github.com/StoneBlue/ASET-Consolidated-Props/issues/31
